# Generated by Django 4.0 on 2022-02-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetinapi', '0002_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
