# Generated by Django 4.0 on 2022-02-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetinapi', '0003_alter_expenses_id_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.FloatField(),
        ),
    ]
